[font]
size = 10 

builtin_box_drawing = true

normal = { family = "BlexMono Nerd Font", style = "Regular" }
bold = { family = "BlexMono Nerd Font", style = "Medium" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Medium Italic"}
