#################################
#             Shadows           #
#################################

shadow = false;
shadow-radius = 7;
# shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;
# shadow-red = 0
# shadow-green = 0
# shadow-blue = 0
# shadow-color = "#000000"
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c"
];
# clip-shadow-above = []
# shadow-exclude-reg = ""
# crop-shadow-to-monitor = false


#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.2;
fade-out-step = 0.2;
fade-delta = 10
# fade-exclude = []
# no-fading-openclose = false
# no-fading-destroyed-argb = false


#################################
#   Transparency / Opacity      #
#################################

# inactive-opacity = 0.95;
# frame-opacity = 1.0
# inactive-opacity-override = false;
# active-opacity = 1.0
# inactive-dim = 0.0
# focus-exclude = [ "class_g = 'Cairo-clock'" ];
# inactive-dim-fixed = 1.0
# opacity-rule = []


#################################
#           Corners             #
#################################

corner-radius = 5 

# Exclude conditions for rounded corners.
rounded-corners-exclude = [ "class_g = 'Rofi'" ];

#################################
#     Background-Blurring       #
#################################
# blur:
# {
#   method = "dual_kawase";
#   size = 20;
# }
# Exclude conditions for background blur.
# blur-background-exclude = []

#################################
#       General Settings        #
#################################

vsync = true;
# backend = "glx";
backend = "xrender";
daemon = true;

#################################
#       Animation Settings      #
#################################

animations = (
{
  triggers = [
    "open", 
    "show",
  ];

  preset = "appear";
  duration = "0.5";
},
{
  triggers = [
    "close", 
    "hide", 
  ];

  preset = "disappear";
  duration = "0.5";
},
{
  triggers = [
    "geometry"
  ];

  preset = "geometry-change";
  duration = "0.4";
})

