#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#3c3836"
bspc config urgent_border_color "#fe8019"
bspc config window_gap          0
bspc config top_padding 140
bspc config right_padding 140
bspc config left_padding 140
bspc config bottom_padding 140
# bspc config center_pseudo_tiled         true

for side in top right left bottom; do bspc config ${side}_monocle_padding -92; done

bspc config split_ratio          0.52
bspc config borderless_monocle  true 
# bspc config gapless_monocle      true
bspc config single_monocle true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating border_width=0

picom &
polybar &
feh --bg-scale ~/debian_grey_swirl_gruv.png &
copyq &
setxkbmap -model pc105 -layout us,ru -option grp:alt_shift_toggle &
dunst &
spoof-dpi -system-proxy -silent &
